jaffle_shop_iceberg:
  outputs:
    dev:
      type: trino
      host: 172.80.0.80
      port: 8080
      user: cagri
      catalog: jaffle_shop_iceberg
      schema: jaffle_shop_sc
      threads: 8
      method: none
  target: dev